name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build debug and release APKs
      run: ./gradlew assembleDebug assembleRelease

    - name: Sign release APK
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # First, check if the unsigned APK exists
        UNSIGNED_APK="app/build/outputs/apk/release/app-release-unsigned.apk"
        if [ ! -f "$UNSIGNED_APK" ]; then
          echo "ERROR: Unsigned release APK not found at $UNSIGNED_APK"
          exit 1
        fi
        
        echo "Signing APK..."
        echo "$KEYSTORE_FILE_BASE64" | base64 --decode > app/release.keystore
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore app/release.keystore \
          -storepass $KEYSTORE_PASSWORD \
          -keypass $KEY_PASSWORD \
          "$UNSIGNED_APK" $ALIAS_NAME
          
        # Rename the signed APK to the final release name
        mv "$UNSIGNED_APK" app/build/outputs/apk/release/app-release.apk
      env:
        KEYSTORE_FILE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        ALIAS_NAME: ${{ secrets.ALIAS_NAME }}

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload release APK
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Clean build artifacts
      run: ./gradlew clean

env:
  KEYSTORE_FILE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  ALIAS_NAME: ${{ secrets.ALIAS_NAME }}


